spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(CDW3cZf4b2DnU3qNDeqJK5lRXLb6mQxIN1xdaBTA1+S1bDhogZlaeUOWMX7QyHF8Tc4oLTmbiW0V/JTv/kHP5NTUeayTmBdkPETvH9vkOxSKYfSPR1JssjMvYnjZxPppV8rKBSU2/jNgP9j8OvkWiVm6jE0X3UdwPYEJ9lzuuwrKLjfR4Hpb8w==)
    username: ENC(yXBx5wdwZUEE3wx0VS/dA22j7rb/w5GU)
    password: ENC(mSe62IQWgHVAhgiPlCnL+z7HlBGfSUsvxDodPhpewxc=)
    type: com.zaxxer.hikari.HikariDataSource # 使用 HikariCP 连接池
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
#      connection-test-query: SELECT 1

  mail:
    host: ${EMIAL_HOST:ENC(qMKUwBybaAKewuGZCDYjQw6tCfRVAO5aIQUolS8L06U=)}
    port: ${EMAIL_PORT:ENC(7RRjEe4cBjcETAkyZ6TBh5zwIw6KrEaz)}
    username: ${EMAIL_USERNAME:ENC(Ndpes2aPfHdQQLG2Ds47yIxEh5/YB2ywTbf7UZ8Re7JgCTjwemDMQw==)}
    password: ${EMAIL_PASSWORD:ENC(IFKjNrj7WUsXTiTldZ8TDgHxBxgkYHXBD5RrrjZ2SlGFXMCaObgqgA==)}
    test-connection: false
  redis:
    host: ${REDIS_HOST:ENC(PdqjmmqM9psXlLIs0m89p7RXZ3mVWQPQ1BYdoHlK1mc=)}
    port: ${REDIS_PORT:ENC(rgpyHtYj/fQOniBDQYFY/V5spo5n01Nb)}
    database: 8
    password: ${REDIS_PASSWORD:ENC(w3YMEo8SvokoWSpmfutV70AO7TBsYuChGTdmc1kzeLiq0+kTllBLdw==)}
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-wait: -1ms # 连接池最大阻塞等待时间（负数表示不限制）
        max-idle: 8 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数
    connect-timeout: 10000

  application:
    name: otow-server

assistant:
  service:
    exception:
      handler:
        disables: springWebExceptionHandler

AIGenerate:
  API_KEY: ${"API_KEY":ENC(phw1kwvm2u+VYf3VLPHVdJ2Qd0/4+nXpR9pA2r9dvhuHwJ6jM2HbUFmwZ2IMmQPX/S7r+nnLXgE=)}
  STRATEGY: ${"DEFAULT_STRATEGY":qw}

captcha:
  mail:
    code-length: 4
  image-code:
    width: 180
    height: 40
    dot-size: 50


oss:
  stsEndPoint: ENC(BScywrt4LG0IHIHqAZLDPm+UTkKuKNjXvk1y+61Aur6GfiSVpEWtB9Gk53SW/z0d)
  bucket: ENC(w0nA1+mA/gEoY2I2ZLR5243/vTc9GnrpMZnNAUUZyUT03xo+6sjfag==)
  accesskeyId: ENC(I1PO+9SO6ViISeGmDVDCG+/V556TmMobZmGpyJDpqfNM5UE3Ulnms7/j++nedhEp)
  accesskeySecret: ENC(DN+VZTq1uSd6zdncmCEvWGqzXr2Xe7I4/fZ701vn6O/eRZp3A/9gvYH3uo4nylcP)
  roleArn: ENC(WL5QvEx60pvQPw/lMQ1aeHuDPoywvVILw1nB2GBP/neachjlb9l+obDBwiS/TBz8TDgYOTygt86LDUBULz/ePA==)
  endpoint: ENC(hyEPeqCP7bT1bpoGaHsUuVI++mkbIKHNGG69MxjAjg9WpTYg9rPLjj57Hw9KmDLNQgOCt3Q/4yo=)
  stsExpire: 3600
  signedExpire: 5
