server:
  port: ${SERVER_PORT:9000}

spring:
  config:
    import: classpath:you-cant-see-that.yml
  profiles:
    active: ${ACTIVE:dev}

mybatis:
  configuration:
    log-impl=org:
      apache:
        ibatis:
          logging:
            stdout:
              StdOutImpl:sa-token:


  token-name: Authorization
  timeout: 259200
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true
  is-read-cookie: false
